const KEY='sports-archive-prototype-v1';
const defaults={settings:{junior:'篮球、足球、排球、乒乓球、羽毛球、800米跑、1000米跑、跳绳、实心球',senior:'篮球、足球、排球、羽毛球、乒乓球、健身跑、健美操、体能训练',siteMax:30,processMax:20,totalMax:50},students:[
  {id:'s1',name:'李然',grade:'初三',className:'1班',track:'junior',event:'篮球',status:'active',scores:[6.4,6.8,6.2,4.7,8,9],note:'篮球项目动作稳定，建议持续提升耐力项目。',updated:'2026-08-31'},
  {id:'s2',name:'王昕',grade:'初三',className:'1班',track:'junior',event:'羽毛球',status:'active',scores:[7.2,6.5,7,5.1,9,8],note:'整体表现良好，注意保持专项训练。',updated:'2026-08-31'},
  {id:'s3',name:'陈子涵',grade:'高一',className:'2班',track:'senior',event:'排球',status:'active',scores:[null,null,null,null,8,null],note:'平时课参与积极。',updated:'2026-08-31'}]};
const rosterSeed=['刘昱檀','李易航','董子铭','高翌宸','黄钰涵','杨梓航','李嘉毅','王思达','魏廷谦','武泽宇','李之薛','张子木','王子谦','赵庆晔','储翊宸','杨斯凯','尼兆宁','吴天骐','赵明朔','王俊然','宋宇尧','马秋皓'];
let state=load(),editing=null,importRows=[];
function seedRoster(){
  let added=0,changed=false;
  state.students.forEach(s=>{if(s.track==='junior'&&(s.grade==='初一'||s.grade==='初二')&&s.event!==''){s.event='';changed=true}});
  rosterSeed.forEach(name=>{
    if(state.students.some(s=>s.grade==='初一'&&s.className==='2班'&&s.name===name))return;
    state.students.push({id:crypto.randomUUID(),name,grade:'初一',className:'2班',track:'junior',event:'',status:'active',scores:[null,null,null,null,null,null],note:'',updated:new Date().toISOString().slice(0,10)}); added++;
  });
  if(added||changed)localStorage.setItem(KEY,JSON.stringify(state));
}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function isJunior(s){return s.track==='junior'}
function total(s){if(!isJunior(s))return s.scores.filter(x=>x!=null).length?Math.round((s.scores.filter(x=>x!=null).reduce((a,b)=>a+b,0)/s.scores.filter(x=>x!=null).length)*10)/10:null;let a=s.scores.slice(0,4),p=s.scores.slice(4,6);if([...a,...p].every(x=>x==null))return null;return Math.min(state.settings.totalMax,[...a,...p].reduce((x,y)=>x+(Number(y)||0),0))}
function pct(s){let t=total(s);return t==null?'—':Math.round(t/state.settings.totalMax*100)+'%'}
function trackName(s){return isJunior(s)?'初中中考体育':'高中体育选修'}
function options(track){return (track==='junior'?state.settings.junior:state.settings.senior).split(/[、,，\n]/).map(x=>x.trim()).filter(Boolean)}
function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){let active=state.students.filter(s=>s.status==='active'),scored=active.filter(s=>total(s)!=null),alerts=active.filter(s=>s.grade==='初三'&&total(s)!=null&&total(s)<state.settings.totalMax*.75),grads=state.students.filter(s=>s.status==='graduated');$('#kpi-active').textContent=active.length;$('#kpi-score').textContent=scored.length;$('#kpi-alert').textContent=alerts.length;$('#kpi-grad').textContent=grads.length;
 $('#recent-list').innerHTML=state.students.slice(0,5).map(s=>`<div class="compact-row"><span><strong>${esc(s.name)}</strong>　${esc(s.grade)} ${esc(s.className)}</span><span>${total(s)==null?'待录入':total(s)+' 分'}</span></div>`).join('')||'<div class="empty">暂无学生档案</div>';
 refreshStudentFilters();renderTable();$('#junior-options').value=state.settings.junior;$('#senior-options').value=state.settings.senior;$('#site-max').value=state.settings.siteMax;$('#process-max').value=state.settings.processMax;$('#total-max').value=state.settings.totalMax;
}
function refreshStudentFilters(){let g=$('#grade-filter'),c=$('#class-filter'),gv=g.value||'all',cv=c.value||'all';let grades=[...new Set(state.students.map(s=>s.grade).filter(Boolean))].sort(),classes=[...new Set(state.students.map(s=>s.className).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN',{numeric:true}));g.innerHTML='<option value="all">全部年级</option>'+grades.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');c.innerHTML='<option value="all">全部班级</option>'+classes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');g.value=grades.includes(gv)?gv:'all';c.value=classes.includes(cv)?cv:'all'}
function renderTable(){let q=$('#student-search').value.trim(),status=$('#status-filter').value,grade=$('#grade-filter').value,className=$('#class-filter').value;let rows=state.students.filter(s=>(status==='all'||s.status===status)&&(grade==='all'||s.grade===grade)&&(className==='all'||s.className===className)&&[s.name,s.grade,s.className].join(' ').includes(q));$('#student-table').innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong><br><span class="muted">更新：${s.updated||'—'}</span></td><td>${esc(s.grade)} / ${esc(s.className)}</td><td>${trackName(s)}</td><td>${esc(s.event||'—')}</td><td>${total(s)==null?'—':total(s)+' / '+state.settings.totalMax+'（'+pct(s)+'）'}</td><td><span class="badge ${s.status==='graduated'?'grad':''}">${s.status==='graduated'?'毕业':'在校'}</span></td><td><button class="row-actions" data-edit="${s.id}">编辑</button>　<button class="row-actions danger" data-delete="${s.id}">删除</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无符合条件的学生。</td></tr>'}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#page-title').textContent={dashboard:'概览',students:'学生档案',import:'导入成绩',settings:'课程与规则',publish:'手机查看发布'}[id]}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));
$('#student-search').oninput=renderTable;$('#status-filter').onchange=renderTable;$('#grade-filter').onchange=renderTable;$('#class-filter').onchange=renderTable;
function fillEvents(track,selected){let e=$('#f-event');e.innerHTML=`<option value="">${track==='junior'?'无选考项目':'请选择项目'}</option>`+options(track).map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('');e.value=selected||''}
function openStudent(s){editing=s||null;$('#dialog-title').textContent=s?'编辑学生档案':'新建学生';$('#student-id').value=s?.id||'';$('#f-name').value=s?.name||'';$('#f-grade').value=s?.grade||'初一';$('#f-class').value=s?.className||'';$('#f-track').value=s?.track||'junior';fillEvents(s?.track||'junior',s?.event);$('#f-status').value=s?.status||'active';['s1','s2','s3','s4','p1','p2'].forEach((id,i)=>$('#'+id).value=s?.scores?.[i]??'');$('#f-note').value=s?.note||'';$('#student-dialog').showModal()}
$('#add-student').onclick=()=>openStudent();$('#f-track').onchange=e=>fillEvents(e.target.value);
$$('.close-student-dialog').forEach(button=>button.addEventListener('click',()=>$('#student-dialog').close()));
$('#student-table').onclick=e=>{let id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;let s=state.students.find(x=>x.id===id);if(e.target.dataset.edit)openStudent(s);else if(confirm(`确定永久删除 ${s.name} 的本机档案吗？此操作不可恢复。`)){state.students=state.students.filter(x=>x.id!==id);save()}};
$('#student-form').addEventListener('submit',e=>{e.preventDefault();let id=$('#student-id').value,old=state.students.find(x=>x.id===id),s={id:id||crypto.randomUUID(),name:$('#f-name').value.trim(),grade:$('#f-grade').value,className:$('#f-class').value.trim(),track:$('#f-track').value,event:$('#f-event').value,status:$('#f-status').value,scores:['s1','s2','s3','s4','p1','p2'].map(i=>$('#'+i).value===''?null:Number($('#'+i).value)),note:$('#f-note').value.trim(),updated:new Date().toISOString().slice(0,10)};if(!s.name||!s.className)return;if(old)Object.assign(old,s);else state.students.unshift(s);$('#student-dialog').close();save()});
function upgrade(){if(!confirm('将执行学年升级：初一→初二、初二→初三、初三→毕业；高一→高二、高二→高三、高三→毕业。确定继续？'))return;let map={'初一':'初二','初二':'初三','高一':'高二','高二':'高三'};state.students.filter(s=>s.status==='active').forEach(s=>{if(['初三','高三'].includes(s.grade))s.status='graduated';else s.grade=map[s.grade]||s.grade;s.updated=new Date().toISOString().slice(0,10)});save();alert('学年升级完成。毕业学生已转入“毕业档案”。')}
$('#batch-promote').onclick=upgrade;$('#promote-settings').onclick=upgrade;
$('#save-settings').onclick=()=>{state.settings.junior=$('#junior-options').value.trim();state.settings.senior=$('#senior-options').value.trim();state.settings.siteMax=Number($('#site-max').value)||30;state.settings.processMax=Number($('#process-max').value)||20;state.settings.totalMax=Number($('#total-max').value)||50;save();alert('课程与试用规则已保存。')};
function parsePaste(text){let lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('请至少粘贴一行表头和一行学生数据。');let split=l=>l.includes('\t')?l.split('\t'):l.split(/\s{2,}|，|,/);let headers=split(lines[0]).map(x=>x.trim());let index=(keys)=>headers.findIndex(h=>keys.some(k=>h.includes(k)));let name=index(['姓名','名字']),cls=index(['班级']),grade=index(['年级']),event=index(['项目','选项','球类']),note=index(['评价','评语']);if(name<0||cls<0||grade<0)throw new Error('未找到“姓名、班级、年级”三项表头。');let scoreIdx=[index(['项目一','800米','1000米']),index(['项目二','引体','斜身','仰卧','实心球','跳绳','纵跳','立定']),index(['项目三','篮球','足球','排球','乒乓','羽毛球']),index(['项目四','体操','长拳','南拳','游泳']),index(['体测']),index(['健康知识','理论'])];return lines.slice(1).map(line=>{let c=split(line);let found=state.students.find(s=>s.status==='active'&&s.name===c[name]&&s.className===c[cls]&&s.grade===c[grade]);return {name:c[name]||'',className:c[cls]||'',grade:c[grade]||'',event:event>=0?c[event]: '',note:note>=0?c[note]:'',scores:scoreIdx.map(i=>i>=0&&c[i]!==''?Number(c[i]):null),found,raw:c}}).filter(r=>r.name)}
$('#preview-import').onclick=()=>{try{importRows=parsePaste($('#paste-area').value);$('#import-preview').innerHTML=`<p class="muted">共识别 ${importRows.length} 行；绿色为匹配现有档案，橙色为新建档案。</p><table class="import-table"><thead><tr><th>姓名</th><th>年级 / 班级</th><th>匹配结果</th><th>项目</th></tr></thead><tbody>${importRows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.grade)} / ${esc(r.className)}</td><td class="${r.found?'match':'new'}">${r.found?'匹配：'+esc(r.found.name):'将新建档案'}</td><td>${esc(r.event||'未识别')}</td></tr>`).join('')}</tbody></table>`;$('#import-actions').classList.remove('hidden')}catch(e){$('#import-preview').textContent=e.message;$('#import-actions').classList.add('hidden')}};
$('#clear-paste').onclick=()=>{$('#paste-area').value='';$('#import-preview').textContent='粘贴内容后点击“识别并预览”。';$('#import-actions').classList.add('hidden')};
$('#confirm-import').onclick=()=>{if(!importRows.length)return;importRows.forEach(r=>{let s=r.found;if(!s){s={id:crypto.randomUUID(),name:r.name,grade:r.grade,className:r.className,track:r.grade.startsWith('高')?'senior':'junior',event:r.event||'',status:'active',scores:[null,null,null,null,null,null],note:'',updated:''};state.students.unshift(s)}if(r.event)s.event=r.event;if(r.note)s.note=r.note;r.scores.forEach((n,i)=>{if(!Number.isNaN(n)&&n!=null)s.scores[i]=n});s.updated=new Date().toISOString().slice(0,10)});save();alert(`已写入 ${importRows.length} 条成绩记录。`);showView('students')};
$('#export-backup').onclick=()=>download('体育档案本机备份.json',JSON.stringify(state,null,2),'application/json');
const enc=new TextEncoder();function b64(u){return btoa(String.fromCharCode(...u))}function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#make-view-data').onclick=async()=>{let pass=$('#publish-password').value;if(pass.length<8){alert('请设置至少 8 位的查看密码。');return}if(!crypto?.subtle){alert('请使用“启动本地服务器.bat”打开本页面后再生成加密文件。');return}let snapshot=state.students.filter(s=>s.status==='active').map(s=>({name:s.name,grade:s.grade,className:s.className,trackName:trackName(s),event:s.event,total:total(s),note:s.note}));let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']),encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(snapshot))));download('viewer-data.enc',JSON.stringify({v:1,s:b64(salt),i:b64(iv),d:b64(encrypted)}),'application/json');$('#publish-result').innerHTML='<strong>已生成加密查看文件。</strong><br>请将下载的 <code>viewer-data.enc</code> 上传并覆盖 GitHub Pages 仓库中的同名文件；手机刷新网页后即可看到最新数据。'};
seedRoster();
render();
