const KEY='sports-archive-prototype-v1';
const defaults={settings:{junior:'篮球、足球、排球、乒乓球、羽毛球、800米跑、1000米跑、跳绳、实心球',senior:'篮球、足球、排球、羽毛球、乒乓球、健身跑、健美操、体能训练',siteMax:30,processMax:20,totalMax:50},students:[],attendanceWeeks:[]};
const rosterSeed=['刘昱檀','李易航','董子铭','高翌宸','黄钰涵','杨梓航','李嘉毅','王思达','魏廷谦','武泽宇','李之薛','张子木','王子谦','赵庆晔','储翊宸','杨斯凯','尼兆宁','吴天骐','赵明朔','王俊然','宋宇尧','马秋皓'];
let state=load(),editing=null,importRows=[],studentPage=1,attendanceWeekStart=mondayOf(new Date()),attendanceGrade='',attendanceClass='';
function seedRoster(){
  let added=0,changed=false;
  state.students.forEach(s=>{if(s.track==='junior'&&(s.grade==='初一'||s.grade==='初二')&&s.event!==''){s.event='';changed=true}});
  rosterSeed.forEach(name=>{
    if(state.students.some(s=>s.grade==='初一'&&s.className==='2班'&&s.name===name))return;
    state.students.push({id:crypto.randomUUID(),name,grade:'初一',className:'2班',track:'junior',event:'',status:'active',scores:[null,null,null,null,null,null],note:'',updated:new Date().toISOString().slice(0,10)}); added++;
  });
  if(added||changed)localStorage.setItem(KEY,JSON.stringify(state));
}
function load(){try{const data=JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults);return normalize(data)}catch{return structuredClone(defaults)}}
function normalize(data){data=data&&typeof data==='object'?data:{};data.settings={...defaults.settings,...(data.settings||{})};if(!Array.isArray(data.students))data.students=[];if(!Array.isArray(data.attendanceWeeks))data.attendanceWeeks=[];data.students.forEach(s=>{if(s.status==='在校'||s.status==='active'||!s.status)s.status='active';else if(s.status==='毕业')s.status='graduated';if(!Array.isArray(s.scores))s.scores=[null,null,null,null,null,null]});return data}
async function syncFromDataFile(){try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)return;const remote=normalize(await response.json());if(remote.students.length){state=remote;localStorage.setItem(KEY,JSON.stringify(state))}else{if(!state.students.length)state=normalize(structuredClone(defaults));seedRoster();await writeDataFile()};render()}catch{} }
async function writeDataFile(){try{await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)})}catch{} }
function statusValue(s){const v=String(s?.status??'active').trim();return v==='毕业'||v==='graduated'?'graduated':'active'}
function save(){localStorage.setItem(KEY,JSON.stringify(state));writeDataFile();render()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function isJunior(s){return s.track==='junior'}
function total(s){if(!isJunior(s))return s.scores.filter(x=>x!=null).length?Math.round((s.scores.filter(x=>x!=null).reduce((a,b)=>a+b,0)/s.scores.filter(x=>x!=null).length)*10)/10:null;let a=s.scores.slice(0,4),p=s.scores.slice(4,6);if([...a,...p].every(x=>x==null))return null;return Math.min(state.settings.totalMax,[...a,...p].reduce((x,y)=>x+(Number(y)||0),0))}
function pct(s){let t=total(s);return t==null?'—':Math.round(t/state.settings.totalMax*100)+'%'}
function mondayOf(date){let d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function weeklyLessons(s){return String(s.grade||'').startsWith('高')?3:5}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function weekDays(start=attendanceWeekStart){return Array.from({length:5},(_,i)=>{let d=new Date(start);d.setDate(d.getDate()+i);return d})}
function attendanceStats(s){let attended=0,absent=0,late=0,recorded=0;for(const w of state.attendanceWeeks||[]){if(w.marks){for(const mark of Object.values(w.marks[s.id]||{})){if(mark.attendance==='pass'||mark.attendance==='fail'){attended++;recorded++}else if(mark.attendance==='absent'){absent++;recorded++}late+=(mark.attendance==='fail'?1:0)+(mark.activities||[]).filter(x=>x==='fail').length}}else{let missed=Number(w.missing?.[s.id]||0),expected=weeklyLessons(s);attended+=Math.max(0,expected-missed);absent+=missed;recorded+=expected}}let equivalentAbsence=absent+late/2,pct=recorded?Math.max(0,Math.round((recorded-equivalentAbsence)/recorded*100)):null;return {attended,absent,late,equivalentAbsence,recorded,pct}}
function attendanceLabel(s){let a=attendanceStats(s);if(a.pct==null)return '<span class="muted">未记录</span>';return `<span class="badge ${a.pct<70?'attendance-alert':''}">${a.pct}%</span><br><span class="muted">课 ${a.recorded}　⭕${a.absent}　迟到${a.late}</span>`}
function trackName(s){return isJunior(s)?'初中中考体育':'高中体育选修'}
function options(track){return (track==='junior'?state.settings.junior:state.settings.senior).split(/[、,，\n]/).map(x=>x.trim()).filter(Boolean)}
function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderExamRules(){if(typeof EXAM_RULES==='undefined'||!$('#exam-category-grid'))return;$('#exam-category-grid').innerHTML=EXAM_RULES.categories.map(c=>`<article class="exam-category"><header><strong>${esc(c.name)}</strong><span>${c.score} 分</span></header><span class="choice-mode">${esc(c.mode)}</span><ul>${c.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('');let table=(selector,headers,rows)=>{$(selector).innerHTML=`<thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody>`};table('#quality-score-table',EXAM_RULES.qualityHeaders,EXAM_RULES.qualityRows);table('#ability-score-table',EXAM_RULES.abilityHeaders,EXAM_RULES.abilityRows);$('#routine-rules').innerHTML=EXAM_RULES.routines.map(r=>`<article class="routine-card"><span class="routine-group">${esc(r.group)}</span><h3>${esc(r.name)}</h3><p>${esc(r.parts)}</p><div class="routine-score"><span>动作质量 5 分</span><span>${r.group.includes('武术')?'演练水平':'动作表现'} 1 分</span></div></article>`).join('')+`<div class="rubric-note"><strong>动作类统一评分说明：</strong>考生在 60 秒内完成相应动作。动作质量按规定顺序和完成情况累计，满分 5 分；整体动作连贯、错误累计不超过 1 次，且节奏、协调或拳种风格符合要求，表现分为 1 分，否则为 0 分。</div>`}
function render(){let active=state.students.filter(s=>statusValue(s)==='active'),scored=active.filter(s=>total(s)!=null),alerts=active.filter(s=>s.grade==='初三'&&total(s)!=null&&total(s)<state.settings.totalMax*.75),grads=state.students.filter(s=>statusValue(s)==='graduated');$('#kpi-active').textContent=active.length;$('#kpi-score').textContent=scored.length;$('#kpi-alert').textContent=alerts.length;$('#kpi-grad').textContent=grads.length;
 const recent=[...state.students].sort((a,b)=>String(b.modifiedAt||b.updated||'').localeCompare(String(a.modifiedAt||a.updated||''))).slice(0,10);
 $('#recent-list').innerHTML=recent.map(s=>`<div class="compact-row"><span><strong>${esc(s.name)}</strong>　${esc(s.grade)} ${esc(s.className)}</span><span>${total(s)==null?'待录入':total(s)+' 分'}</span></div>`).join('')||'<div class="empty">暂无学生档案</div>';
 refreshStudentFilters();renderTable();renderAttendance();renderExamRules();$('#junior-options').value=state.settings.junior;$('#senior-options').value=state.settings.senior;$('#site-max').value=state.settings.siteMax;$('#process-max').value=state.settings.processMax;$('#total-max').value=state.settings.totalMax;
}
function refreshStudentFilters(){let g=$('#grade-filter'),c=$('#class-filter');if(!g||!c)return;let gv=g.value||'all',cv=c.value||'all';let gradeSet=new Set(['初一','初二','初三','高一','高二','高三']);let classSet=new Set(['1班','2班','3班','4班','5班','6班','7班','8班','9班','10班']);state.students.forEach(s=>{if(s.grade)gradeSet.add(String(s.grade).trim());if(s.className)classSet.add(String(s.className).trim())});let grades=[...gradeSet].sort(),classes=[...classSet].sort((a,b)=>a.localeCompare(b,'zh-CN',{numeric:true}));g.innerHTML='<option value="all">全部年级</option>'+grades.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');c.innerHTML='<option value="all">全部班级</option>'+classes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');g.value=grades.includes(gv)?gv:'all';c.value=classes.includes(cv)?cv:'all'}
function renderTable(){let q=$('#student-search').value.trim(),status=$('#status-filter').value,grade=$('#grade-filter').value,className=$('#class-filter').value;let rows=state.students.filter(s=>(status==='all'||statusValue(s)===status)&&(grade==='all'||String(s.grade||'').trim()===grade)&&(className==='all'||String(s.className||'').trim()===className)&&[s.name,s.grade,s.className].join(' ').includes(q));let pages=Math.max(1,Math.ceil(rows.length/20));studentPage=Math.min(studentPage,pages);let visible=rows.slice((studentPage-1)*20,studentPage*20);$('#student-table').innerHTML=visible.map(s=>`<tr><td><strong>${esc(s.name)}</strong><br><span class="muted">更新：${s.updated||'—'}</span></td><td>${esc(s.grade)} / ${esc(s.className)}</td><td>${trackName(s)}</td><td>${esc(s.event||'—')}</td><td>${total(s)==null?'—':total(s)+' / '+state.settings.totalMax+'（'+pct(s)+'）'}</td><td>${attendanceLabel(s)}</td><td><span class="badge ${statusValue(s)==='graduated'?'grad':''}">${statusValue(s)==='graduated'?'毕业':'在校'}</span></td><td><button class="row-actions" data-edit="${s.id}">编辑</button>　<button class="row-actions danger" data-delete="${s.id}">删除</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">暂无符合条件的学生。</td></tr>';let pager=$('#student-pagination');if(pager)pager.innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button class="row-actions ${i+1===studentPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join(''):`<span class="muted">共 ${rows.length} 名学生</span>`}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#page-title').textContent={dashboard:'概览',students:'学生档案',attendance:'考勤输入',import:'导入成绩',settings:'课程与规则',publish:'手机查看发布'}[id]}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));
$('#student-search').oninput=()=>{studentPage=1;renderTable()};$('#status-filter').onchange=()=>{studentPage=1;renderTable()};$('#grade-filter').onchange=()=>{studentPage=1;renderTable()};$('#class-filter').onchange=()=>{studentPage=1;renderTable()};$('#student-pagination').onclick=e=>{if(e.target.dataset.page){studentPage=Number(e.target.dataset.page);renderTable()}};
function fillEvents(track,selected){let e=$('#f-event');e.innerHTML=`<option value="">${track==='junior'?'无选考项目':'请选择项目'}</option>`+options(track).map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('');e.value=selected||''}
function openStudent(s){editing=s||null;$('#dialog-title').textContent=s?'编辑学生档案':'新建学生';$('#student-id').value=s?.id||'';$('#f-name').value=s?.name||'';$('#f-grade').value=s?.grade||'初一';$('#f-class').value=s?.className||'';$('#f-track').value=s?.track||'junior';fillEvents(s?.track||'junior',s?.event);$('#f-status').value=s?.status||'active';['s1','s2','s3','s4','p1','p2'].forEach((id,i)=>$('#'+id).value=s?.scores?.[i]??'');$('#f-note').value=s?.note||'';$('#student-dialog').showModal()}
$('#add-student').onclick=()=>openStudent();$('#f-track').onchange=e=>fillEvents(e.target.value);
$$('.close-student-dialog').forEach(button=>button.addEventListener('click',()=>$('#student-dialog').close()));
$('#student-table').onclick=e=>{let id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;let s=state.students.find(x=>x.id===id);if(e.target.dataset.edit)openStudent(s);else if(confirm(`确定永久删除 ${s.name} 的本机档案吗？此操作不可恢复。`)){state.students=state.students.filter(x=>x.id!==id);save()}};
$('#student-form').addEventListener('submit',e=>{e.preventDefault();let id=$('#student-id').value,old=state.students.find(x=>x.id===id),now=new Date().toISOString(),s={id:id||crypto.randomUUID(),name:$('#f-name').value.trim(),grade:$('#f-grade').value,className:$('#f-class').value.trim(),track:$('#f-track').value,event:$('#f-event').value,status:$('#f-status').value,scores:['s1','s2','s3','s4','p1','p2'].map(i=>$('#'+i).value===''?null:Number($('#'+i).value)),note:$('#f-note').value.trim(),updated:now.slice(0,10),modifiedAt:now};if(!s.name||!s.className)return;if(old)Object.assign(old,s);else state.students.unshift(s);$('#student-dialog').close();save()});
function upgrade(){if(!confirm('将执行学年升级：初一→初二、初二→初三、初三→毕业；高一→高二、高二→高三、高三→毕业。确定继续？'))return;let map={'初一':'初二','初二':'初三','高一':'高二','高二':'高三'};state.students.filter(s=>s.status==='active').forEach(s=>{if(['初三','高三'].includes(s.grade))s.status='graduated';else s.grade=map[s.grade]||s.grade;s.updated=new Date().toISOString().slice(0,10)});save();alert('学年升级完成。毕业学生已转入“毕业档案”。')}
const batchPromote=$('#batch-promote');if(batchPromote)batchPromote.onclick=upgrade;$('#promote-settings').onclick=upgrade;
function activeAttendanceStudents(){return state.students.filter(s=>statusValue(s)==='active'&&s.grade===attendanceGrade&&s.className===attendanceClass)}
function weekEntry(create=false){let key=dateKey(attendanceWeekStart),week=state.attendanceWeeks.find(w=>w.key===key);if(!week&&create){week={id:crypto.randomUUID(),key,start:key,label:`${key} 当周`,marks:{},updated:new Date().toISOString()};state.attendanceWeeks.push(week)}if(week&&!week.marks)week.marks={};return week}
function studentDay(week,studentId,dayKey,create=false){if(!week)return null;if(create){week.marks[studentId]??={};week.marks[studentId][dayKey]??={attendance:'',activities:['','','']}}return week.marks?.[studentId]?.[dayKey]||null}
function markButtons(value,studentId,day,field,index=''){return `<div class="mark-options" data-student="${studentId}" data-day="${day}" data-field="${field}" data-index="${index}"><button class="mark-choice absent ${value==='absent'?'selected':''}" data-mark="absent" title="旷课">⭕</button><button class="mark-choice fail ${value==='fail'?'selected':''}" data-mark="fail" title="未完成，记迟到一次">×</button><button class="mark-choice pass ${value==='pass'?'selected':''}" data-mark="pass" title="已完成">✓</button></div>`}
function refreshAttendanceFilters(){let grades=[...new Set(state.students.filter(s=>statusValue(s)==='active').map(s=>s.grade))].sort(),grade=$('#attendance-grade'),cls=$('#attendance-class');if(!attendanceGrade||!grades.includes(attendanceGrade))attendanceGrade=grades[0]||'';grade.innerHTML=grades.map(x=>`<option ${x===attendanceGrade?'selected':''}>${esc(x)}</option>`).join('');let classes=[...new Set(state.students.filter(s=>statusValue(s)==='active'&&s.grade===attendanceGrade).map(s=>s.className))].sort((a,b)=>a.localeCompare(b,'zh-CN',{numeric:true}));if(!attendanceClass||!classes.includes(attendanceClass))attendanceClass=classes[0]||'';cls.innerHTML=classes.map(x=>`<option ${x===attendanceClass?'selected':''}>${esc(x)}</option>`).join('')}
function renderAttendance(){if(!$('#attendance-body'))return;refreshAttendanceFilters();let days=weekDays(),limit=attendanceGrade.startsWith('高')?3:5,shown=days.slice(0,limit),students=activeAttendanceStudents(),week=weekEntry(false),weekEnd=shown.at(-1)||days[4];$('#attendance-week-label').textContent=`${dateKey(days[0])} 至 ${dateKey(weekEnd)}　${attendanceGrade}${attendanceClass}`;let h1='<tr><th rowspan="2" class="sticky-name">姓名</th>',h2='<tr>';shown.forEach((d,i)=>{h1+=`<th colspan="4">${['周一','周二','周三','周四','周五'][i]}<small>${d.getMonth()+1}/${d.getDate()}</small></th>`;h2+='<th>到课</th><th>练1</th><th>练2</th><th>练3</th>'});h1+='<th rowspan="2" class="attendance-stat-head">本周统计</th></tr>';h2+='</tr>';$('#attendance-head').innerHTML=h1+h2;$('#attendance-body').innerHTML=students.map(s=>{let present=0,absent=0,late=0,cells='';shown.forEach(d=>{let dk=dateKey(d),m=studentDay(week,s.id,dk,false)||{attendance:'',activities:['','','']};if(m.attendance==='pass'||m.attendance==='fail')present++;if(m.attendance==='absent')absent++;late+=(m.attendance==='fail'?1:0)+(m.activities||[]).filter(x=>x==='fail').length;cells+=`<td>${markButtons(m.attendance,s.id,dk,'attendance')}</td>`;for(let i=0;i<3;i++)cells+=`<td>${markButtons(m.activities?.[i]||'',s.id,dk,'activity',i)}</td>`});let recorded=present+absent,pct=recorded?Math.max(0,Math.round((recorded-absent-late/2)/recorded*100)):null;return `<tr><td class="sticky-name"><strong>${esc(s.name)}</strong></td>${cells}<td class="attendance-stat"><strong class="${pct!=null&&pct<70?'low':''}">${pct==null?'—':pct+'%'}</strong><small>课${recorded}　⭕${absent}　迟${late}</small></td></tr>`}).join('')||'<tr><td colspan="22" class="empty">当前班级暂无学生。</td></tr>';let totals=students.reduce((a,s)=>{let x=attendanceStats(s);a.absent+=x.absent;a.late+=x.late;return a},{absent:0,late:0});$('#attendance-summary').innerHTML=`<span>本班 ${students.length} 人</span><span>累计旷课 ${totals.absent} 次</span><span>累计迟到 ${totals.late} 次</span><span>折算旷课 ${totals.absent+Math.floor(totals.late/2)} 次</span><span class="muted">空白项目不统计</span>`}
function persistAttendance(){localStorage.setItem(KEY,JSON.stringify(state));writeDataFile();renderAttendance();renderTable()}
$('#attendance-grade').onchange=e=>{attendanceGrade=e.target.value;attendanceClass='';renderAttendance()};$('#attendance-class').onchange=e=>{attendanceClass=e.target.value;renderAttendance()};
$('#attendance-prev').onclick=()=>{attendanceWeekStart.setDate(attendanceWeekStart.getDate()-7);renderAttendance()};$('#attendance-next').onclick=()=>{attendanceWeekStart.setDate(attendanceWeekStart.getDate()+7);renderAttendance()};$('#attendance-today').onclick=()=>{attendanceWeekStart=mondayOf(new Date());renderAttendance()};$('#attendance-finish').onclick=()=>{attendanceWeekStart.setDate(attendanceWeekStart.getDate()+7);renderAttendance()};
$('#attendance-body').onclick=e=>{let button=e.target.closest('[data-mark]'),group=e.target.closest('.mark-options');if(!button||!group)return;let week=weekEntry(true),mark=studentDay(week,group.dataset.student,group.dataset.day,true),value=button.dataset.mark,field=group.dataset.field,index=Number(group.dataset.index),current=field==='attendance'?mark.attendance:mark.activities[index];value=current===value?'':value;if(field==='attendance'){mark.attendance=value;if(value==='absent')mark.activities=['absent','absent','absent'];else if(!value)mark.activities=mark.activities.map(x=>x==='absent'?'':x)}else{mark.activities[index]=value;if(value==='absent'){mark.attendance='absent';mark.activities=['absent','absent','absent']}else if(value==='fail'||value==='pass')mark.attendance='pass'}week.updated=new Date().toISOString();persistAttendance()};
$('#save-settings').onclick=()=>{state.settings.junior=$('#junior-options').value.trim();state.settings.senior=$('#senior-options').value.trim();state.settings.siteMax=Number($('#site-max').value)||30;state.settings.processMax=Number($('#process-max').value)||20;state.settings.totalMax=Number($('#total-max').value)||50;save();alert('课程与试用规则已保存。')};
function parsePaste(text){let lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('请至少粘贴一行表头和一行学生数据。');let split=l=>l.includes('\t')?l.split('\t'):l.split(/\s{2,}|，|,/);let headers=split(lines[0]).map(x=>x.trim());let index=(keys)=>headers.findIndex(h=>keys.some(k=>h.includes(k)));let name=index(['姓名','名字']),cls=index(['班级']),grade=index(['年级']),event=index(['项目','选项','球类']),note=index(['评价','评语']);if(name<0||cls<0||grade<0)throw new Error('未找到“姓名、班级、年级”三项表头。');let scoreIdx=[index(['项目一','800米','1000米']),index(['项目二','引体','斜身','仰卧','实心球','跳绳','纵跳','立定']),index(['项目三','篮球','足球','排球','乒乓','羽毛球']),index(['项目四','体操','长拳','南拳','游泳']),index(['体测']),index(['健康知识','理论'])];return lines.slice(1).map(line=>{let c=split(line);let found=state.students.find(s=>s.status==='active'&&s.name===c[name]&&s.className===c[cls]&&s.grade===c[grade]);return {name:c[name]||'',className:c[cls]||'',grade:c[grade]||'',event:event>=0?c[event]: '',note:note>=0?c[note]:'',scores:scoreIdx.map(i=>i>=0&&c[i]!==''?Number(c[i]):null),found,raw:c}}).filter(r=>r.name)}
$('#preview-import').onclick=()=>{try{importRows=parsePaste($('#paste-area').value);$('#import-preview').innerHTML=`<p class="muted">共识别 ${importRows.length} 行；绿色为匹配现有档案，橙色为新建档案。</p><table class="import-table"><thead><tr><th>姓名</th><th>年级 / 班级</th><th>匹配结果</th><th>项目</th></tr></thead><tbody>${importRows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.grade)} / ${esc(r.className)}</td><td class="${r.found?'match':'new'}">${r.found?'匹配：'+esc(r.found.name):'将新建档案'}</td><td>${esc(r.event||'未识别')}</td></tr>`).join('')}</tbody></table>`;$('#import-actions').classList.remove('hidden')}catch(e){$('#import-preview').textContent=e.message;$('#import-actions').classList.add('hidden')}};
$('#clear-paste').onclick=()=>{$('#paste-area').value='';$('#import-preview').textContent='粘贴内容后点击“识别并预览”。';$('#import-actions').classList.add('hidden')};
$('#confirm-import').onclick=()=>{if(!importRows.length)return;importRows.forEach(r=>{let s=r.found;if(!s){s={id:crypto.randomUUID(),name:r.name,grade:r.grade,className:r.className,track:r.grade.startsWith('高')?'senior':'junior',event:r.event||'',status:'active',scores:[null,null,null,null,null,null],note:'',updated:''};state.students.unshift(s)}if(r.event)s.event=r.event;if(r.note)s.note=r.note;r.scores.forEach((n,i)=>{if(!Number.isNaN(n)&&n!=null)s.scores[i]=n});s.updated=new Date().toISOString().slice(0,10)});save();alert(`已写入 ${importRows.length} 条成绩记录。`);showView('students')};
$('#export-backup').onclick=()=>download('体育档案本机备份.json',JSON.stringify(state,null,2),'application/json');
const enc=new TextEncoder();function b64(u){return btoa(String.fromCharCode(...u))}function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#make-view-data').onclick=async()=>{let pass=$('#publish-password').value;if(pass.length<8){alert('请设置至少 8 位的查看密码。');return}if(!crypto?.subtle){alert('请使用“启动体育档案”打开本页面后再生成加密文件。');return}let snapshot={version:2,generatedAt:new Date().toISOString(),settings:state.settings,attendanceWeeks:state.attendanceWeeks||[],students:state.students.filter(s=>statusValue(s)==='active').map(s=>({id:s.id,name:s.name,grade:s.grade,className:s.className,trackName:trackName(s),event:s.event,scores:s.scores,total:total(s),note:s.note,updated:s.updated,attendance:attendanceStats(s)}))};let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']),encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(snapshot))));download('viewer-data.enc',JSON.stringify({v:1,s:b64(salt),i:b64(iv),d:b64(encrypted)}),'application/json');$('#publish-result').innerHTML='<strong>已生成完整加密查看文件。</strong><br>文件包含学生档案、成绩、考勤和查看页所需数据。请覆盖 GitHub Pages 仓库中的 <code>viewer-data.enc</code>。'};
seedRoster();
render();
syncFromDataFile();
