let archive={version:1,students:[],attendanceWeeks:[],settings:{}};
const enc=new TextEncoder(),dec=new TextDecoder(),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function key(password,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['decrypt'])}
function normalizePayload(payload){if(Array.isArray(payload))return {version:1,students:payload,attendanceWeeks:[],settings:{}};return {version:payload.version||2,students:Array.isArray(payload.students)?payload.students:[],attendanceWeeks:Array.isArray(payload.attendanceWeeks)?payload.attendanceWeeks:[],settings:payload.settings||{},generatedAt:payload.generatedAt||''}}
function formatScore(value){return value==null?'—':`${Number(value).toFixed(1).replace('.0','')} 分`}
function attendanceOf(s){return s.attendance||{pct:null,recorded:0,absent:0,late:0}}
function renderOverview(){let students=archive.students,a=students.filter(s=>s.total!=null),alerts=students.filter(s=>attendanceOf(s).pct!=null&&attendanceOf(s).pct<70);$('#viewer-active').textContent=students.length;$('#viewer-scored').textContent=a.length;$('#viewer-alert').textContent=alerts.length;$('#viewer-weeks').textContent=archive.attendanceWeeks.length;$('#snapshot-time').textContent=archive.generatedAt?`数据生成：${new Date(archive.generatedAt).toLocaleString('zh-CN')}`:'旧版查看数据';$('#viewer-recent').innerHTML=students.slice(0,10).map(s=>`<div class="viewer-list-row"><span><strong>${esc(s.name)}</strong>　${esc(s.grade)} ${esc(s.className)}</span><span>${formatScore(s.total)}</span></div>`).join('')||'<div class="empty-state">暂无学生档案</div>'}
function fillSelect(el,values,allLabel){let old=el.value;el.innerHTML=`<option value="all">${allLabel}</option>`+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');el.value=values.includes(old)?old:'all'}
function setupStudentFilters(){let grades=[...new Set(archive.students.map(s=>s.grade).filter(Boolean))].sort(),classes=[...new Set(archive.students.map(s=>s.className).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN',{numeric:true}));fillSelect($('#viewer-grade'),grades,'全部年级');fillSelect($('#viewer-class'),classes,'全部班级');renderStudents()}
function renderStudents(){let q=$('#viewer-search').value.trim(),grade=$('#viewer-grade').value,className=$('#viewer-class').value,rows=archive.students.filter(s=>(grade==='all'||s.grade===grade)&&(className==='all'||s.className===className)&&[s.name,s.grade,s.className].join(' ').includes(q));$('#viewer-student-list').innerHTML=rows.map(s=>{let a=attendanceOf(s),parts=Array.isArray(s.scores)?s.scores.map((x,i)=>x==null?'—':`项目${i+1} ${x}`).join('　'):'';return `<article class="student-readonly"><div><h3>${esc(s.name)}</h3><p>${esc(s.grade)} / ${esc(s.className)}　${esc(s.trackName||'')}</p><p class="muted">${esc(s.event||'无选考项目')}</p></div><div class="metric"><span class="muted">本学期总评</span><strong>${formatScore(s.total)}</strong><small class="score-parts">${esc(parts)}</small></div><div class="metric"><span class="muted">考勤比例</span><strong class="${a.pct!=null&&a.pct<70?'low':''}">${a.pct==null?'未记录':a.pct+'%'}</strong><small>课 ${a.recorded||0}　⭕${a.absent||0}　迟到${a.late||0}</small></div><div><span class="muted">教师评价</span><p>${esc(s.note||'—')}</p></div></article>`}).join('')||'<div class="empty-state">未找到符合条件的学生</div>'}
function dateFromKey(key,offset=0){let d=new Date(`${key}T00:00:00`);d.setDate(d.getDate()+offset);return d}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setupAttendanceFilters(){let weeks=[...archive.attendanceWeeks].sort((a,b)=>String(b.start||b.key||'').localeCompare(String(a.start||a.key||''))),week=$('#viewer-week');week.innerHTML=weeks.map(w=>`<option value="${esc(w.id)}">${esc(w.label||w.start||w.key||'未命名周次')}</option>`).join('')||'<option value="">暂无考勤记录</option>';let grades=[...new Set(archive.students.map(s=>s.grade).filter(Boolean))].sort();$('#viewer-attendance-grade').innerHTML=grades.map(x=>`<option>${esc(x)}</option>`).join('');refreshAttendanceClasses();renderAttendance()}
function refreshAttendanceClasses(){let grade=$('#viewer-attendance-grade').value,classes=[...new Set(archive.students.filter(s=>s.grade===grade).map(s=>s.className))].sort((a,b)=>a.localeCompare(b,'zh-CN',{numeric:true})),el=$('#viewer-attendance-class'),old=el.value;el.innerHTML=classes.map(x=>`<option>${esc(x)}</option>`).join('');if(classes.includes(old))el.value=old}
function statusSymbol(value){return value==='absent'?'⭕':value==='fail'?'×':value==='pass'?'✓':''}
function renderAttendance(){let week=archive.attendanceWeeks.find(w=>w.id===$('#viewer-week').value),grade=$('#viewer-attendance-grade').value,className=$('#viewer-attendance-class').value,students=archive.students.filter(s=>s.grade===grade&&s.className===className);if(!week){$('#viewer-attendance-list').innerHTML='<div class="empty-state">尚未发布考勤记录</div>';return}let start=week.start||week.key,dayNames=['周一','周二','周三','周四','周五'],days=Array.from({length:grade.startsWith('高')?3:5},(_,i)=>{let d=dateFromKey(start,i);return {key:dateKey(d),label:`${dayNames[i]} ${d.getMonth()+1}/${d.getDate()}`}});$('#viewer-attendance-list').innerHTML=students.map(s=>{let marks=week.marks?.[s.id]||{},cards=days.map(d=>{let m=marks[d.key]||{attendance:'',activities:[]},activities=(m.activities||[]).map((x,i)=>x?`练${i+1}${statusSymbol(x)}`:'').filter(Boolean);return `<div class="attendance-day"><strong>${d.label}</strong><div class="day-marks">${statusSymbol(m.attendance)||'—'}</div><small>${activities.join('　')||'无练习记录'}</small></div>`}).join('');return `<article class="attendance-student"><div class="attendance-student-head"><h3>${esc(s.name)}</h3><span class="muted">累计考勤 ${attendanceOf(s).pct==null?'—':attendanceOf(s).pct+'%'}</span></div><div class="attendance-days">${cards}</div></article>`}).join('')||'<div class="empty-state">当前班级暂无学生</div>'}
function renderRuleTable(selector,headers,rows){$(selector).innerHTML=`<thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody>`}
function renderRules(){if(typeof EXAM_RULES==='undefined')return;$('#viewer-category-grid').innerHTML=EXAM_RULES.categories.map(c=>`<article class="exam-category"><header><strong>${esc(c.name)}</strong><span>${c.score} 分</span></header><span class="choice-mode">${esc(c.mode)}</span><ul>${c.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('');renderRuleTable('#viewer-quality-table',EXAM_RULES.qualityHeaders,EXAM_RULES.qualityRows);renderRuleTable('#viewer-ability-table',EXAM_RULES.abilityHeaders,EXAM_RULES.abilityRows);$('#viewer-routine-rules').innerHTML=EXAM_RULES.routines.map(r=>`<article class="routine-card"><span class="routine-group">${esc(r.group)}</span><h3>${esc(r.name)}</h3><p>${esc(r.parts)}</p><div class="routine-score"><span>动作质量 5 分</span><span>${r.group.includes('武术')?'演练水平':'动作表现'} 1 分</span></div></article>`).join('')}
function initializeViewer(){renderOverview();setupStudentFilters();setupAttendanceFilters();renderRules();$('#unlock').classList.add('hidden');$('#viewer').classList.remove('hidden')}
$('#unlock-btn').onclick=async()=>{try{let r=await fetch('viewer-data.enc',{cache:'no-store'});if(!r.ok)throw new Error();let b=await r.json(),salt=Uint8Array.from(atob(b.s),c=>c.charCodeAt(0)),iv=Uint8Array.from(atob(b.i),c=>c.charCodeAt(0)),data=Uint8Array.from(atob(b.d),c=>c.charCodeAt(0)),payload=JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},await key($('#password').value,salt),data)));archive=normalizePayload(payload);initializeViewer()}catch{$('#unlock-msg').textContent='无法打开：密码错误，或尚未发布查看文件。'}};
$$('[data-viewer-tab]').forEach(b=>b.onclick=()=>{$$('[data-viewer-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.viewer-panel').forEach(x=>x.classList.toggle('active',x.id===`viewer-${b.dataset.viewerTab}`))});
$('#viewer-search').oninput=renderStudents;$('#viewer-grade').onchange=renderStudents;$('#viewer-class').onchange=renderStudents;$('#viewer-week').onchange=renderAttendance;$('#viewer-attendance-grade').onchange=()=>{refreshAttendanceClasses();renderAttendance()};$('#viewer-attendance-class').onchange=renderAttendance;
